twig:
  file_name_pattern: '*.twig'
  globals:
    default_image_url: '%app.image_default%'
  form_themes:
    - tailwind_2_layout.html.twig
    - shared/resources/form/form_theme.html.twig

when@test:
  twig:
    strict_variables: true
