web:
  resource:
    path: ../src/WebContext/Presenter/Controller/
    namespace: Websymphonie\WebContext\Presenter\Controller
  type: attribute
  prefix: '/'

auth:
  resource:
    path: ../src/AuthContext/Presenter/Controller/
    namespace: Websymphonie\AuthContext\Presenter\Controller
  type: attribute
  prefix: '/auth'

identity:
  resource:
    path: ../src/IdentityContext/Presenter/Controller/
    namespace: Websymphonie\IdentityContext\Presenter\Controller
  type: attribute
  prefix: '/admin/identity'

member:
  resource:
    path: ../src/IdentityContext/Presenter/Controller/Member/
    namespace: Websymphonie\IdentityContext\Presenter\Controller\Member
  type: attribute
  prefix: '/'

log:
  resource:
    path: ../src/LogContext/Presenter/Controller/
    namespace: Websymphonie\LogContext\Presenter\Controller
  type: attribute
  prefix: '/admin/log'

notification:
  resource:
    path: ../src/NotificationContext/Presenter/Controller/
    namespace: Websymphonie\NotificationContext\Presenter\Controller
  type: attribute
  prefix: '/admin/notification'

content:
  resource:
    path: ../src/ContentContext/Presenter/Controller/
    namespace: Websymphonie\ContentContext\Presenter\Controller
  type: attribute
  prefix: '/admin/content'

shared:
  resource:
    path: ../src/SharedContext/Presenter/Controller/
    namespace: Websymphonie\SharedContext\Presenter\Controller
  type: attribute
  prefix: '/shared'

# SUPER ADMIN
admin_root:
  path: '/admin'
  controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController
  defaults:
    route: app_admin
    permanent: false

admin:
  resource:
    path: ../src/AdminContext/Presenter/Controller/
    namespace: Websymphonie\AdminContext\Presenter\Controller
  type: attribute
  prefix: '/admin'
